framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    ide:                  ~
    test:                 ~
    default_locale:       en

    # csrf configuration
    csrf_protection:
        enabled:              false

    # form configuration
    form:
        enabled:              true

    # esi configuration
    esi:
        enabled:              false

    # fragments configuration
    fragments:
        enabled:              false

    # session configuration
    session:
        enabled:              false

    # serializer configuration
    serializer:
       enabled: false

    # templating configuration
    templating:
        engines: 
            - twig

    # translator configuration
    translator:
        enabled:              false

    # PHP errors handling configuration
    php_errors:
        log:                  false
        throw:                '%kernel.debug%'
