nelmio_api_doc:
    documentation:
        info:
            title: EmberSy Fire
            description: A Nifty Kickstart package!
            version: 1.0.0
        securityDefinitions:
            auth_token:
                type: apiKey
                description: 'Authorization Token in the headers as name: Authorization'
                name: 'Authorization'
                in: header
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc$|doc.json$)) # Accepts routes under /api except /api/doc
